### ISSUE TITLE
Launch RDP not working

### ISSUE THREAD

**Issue by phil210802** [OneIdentity/SCALUS#138]
I am able to connect to SSH and Telnet sessions using Scalus, however when I try and use Scalus to connect to RDP I am prompted by SPS to enter a target server.

Please see attached.
![scalus message (while trying to load rdp)](https://github.com/OneIdentity/SCALUS/assets/149203917/5a61147e-10b4-4969-a6fc-0e7395ba6256)
![sps enter target server](https://github.com/OneIdentity/SCALUS/assets/149203917/89ab0bf5-007f-4435-a7a6-0b4f5473ef70)

**Comment by phil210802** [comment]
If however I download the RDP file and launch it, it works as expected.

**Comment by phil210802** [comment]
web.config

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath=".\scalus.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>

**Comment by phil210802** [comment]
appsettings.json

{
  "Logging": {
    "FileName": "scalus.log",
    "MinLevel": "Information",
    "Console": true
  },
  "Configuration": {
    "FileName": "SCALUS.json"
  },
  "Lifetime": {
    "IgnoreShutdown": false
  }
}

**Comment by CodyBatt** [comment]
This is the file we need:

![image](https://github.com/OneIdentity/SCALUS/assets/1326182/ec455f9b-8fab-4929-ab4b-e76851410ad0)

**Comment by phil210802** [comment]
Sorry.

Here you go.

Thanks.
[scalus.json](https://github.com/OneIdentity/SCALUS/files/13252074/scalus.json)

**Comment by CodyBatt** [comment]
What version of windows and what version of SPP?

**Comment by phil210802** [comment]
7.4

**Comment by phil210802** [comment]
Windows 10 22H2 (OS Build 19045.3570)

**Comment by CodyBatt** [comment]
Scalus takes the URL from SPP and parses it into properties then writes out a temporary RDP file according to one of the installed templates and launches it with RDP client. 

Either:

- The parser isn't  parsing the URL correctly (SCALUS bug)
- The URL has bad data (SPP bug)
- Or the template isn't correct (Configuration)
 
 With the full text of the URL being launched, the correct RDP file and the incorrect RDP file it should be possible to see what's going wrong and reproduce it. 
 
Can you try again and paste the full text of the URL being launched:

![image](https://github.com/OneIdentity/SCALUS/assets/1326182/8b4434b3-8ebe-46be-9849-9ea22007260d)

The contents of the temporary RDP file (it's just a text file):
![image](https://github.com/OneIdentity/SCALUS/assets/1326182/75d3b6a1-f16b-4824-93f2-417c452d5634)

And the contents of the working RDP file returned from SPP?

**Comment by phil210802** [comment]
@CodyBatt  & @JaredCuster 

Details as per request.

Thx.

![Uploading image.png…]()
[scalas created rdp file.txt](https://github.com/OneIdentity/SCALUS/files/13264724/scalas.created.rdp.file.txt)
[spp created rdp file.txt](https://github.com/OneIdentity/SCALUS/files/13264725/spp.created.rdp.file.txt)
[WinRdpTemplate.txt](https://github.com/OneIdentity/SCALUS/files/13264726/WinRdpTemplate.txt)

**Comment by phil210802** [comment]
![image](https://github.com/OneIdentity/SCALUS/assets/149203917/dd683c0d-00fa-461d-81b9-46248b6100f1)

**Comment by CodyBatt** [comment]
So this is the working username:
```
username:s:vaultaddress~20.5.19.50%token~A5HabfCeZPZDk6h2Bo4BqyAWiB4JZvNNbfwqZHWxBjXLS8CHmJGKBy63Ag8bmWZWRtu75b2vd3VGyVg2W4%admin_1@pf1idlab.local%20.5.19.11
```

And this is the incorrect username. Pretty obviously has invalid characters:
```
username:s:pf1idlab.local\vaultaddress~20.5.19.50%token~A5KvBHRJDcscWqGXYsHSw4xynemEGEcGQeAbQcCSqa2NbGRPzkXNREPqrfWN238kXuZtyJi4mLs66LDaj9�min_1 .5.19.11:3389
```
Defintely looks like a scalus bug.

**Comment by JaredCuster** [comment]
@phil210802 unable reproduce, can you attach the scalus.log file please.
