### ISSUE TITLE
RDP Tempfile Name

### ISSUE THREAD

**Issue by SebaMartin** [OneIdentity/SCALUS#30]
When opening an RDP session, SCALUS creates a temporary RDP file to start the session. This file name shows up in the RDP window name. For example "tmpADB1.rdp" (Image attached)

![RDP FileName](https://user-images.githubusercontent.com/85624819/121357867-70073380-c932-11eb-982b-e35137a62293.png)

The Safeguard Client uses a combination of AssetName, AccountName and ConnectionID for the RDP file which makes it easier to identify the correct RDP window if you are using multiple windows simultaneous.

This is not really an "issue" but I couldn't find a way to create a "suggestion"

PS: I couldn't find the lines in code where this temp file is created and named. If you can tell me where this is done, maybe I can try to fix this myself somehow. I still believe this should be fixed in the final Release into the Safeguard Product.

**Comment by MiriamMcMahon** [comment]
Thanks for the suggestion. I agree , it would be helpful to distinguish between multiple sessions.  I will put in a fix for it.

**Comment by MiriamMcMahon** [comment]
For safeguard URLs, I've changed it to use the target asset hostname and accountname to name the temp file in scalus (the Safeguard asset name is not included in the URL, so scalus doesnt have access to it).
I also  had to replace the "." character with ' ~ ' to avoid Microsoft RDP  truncating the title at the first '.' in the hostname, so the title now looks something like this
_SG-myasset~mydomain ~com_jsmith_d0cba338-12bc-4209-9eb8-4a4b5c48623d - sps-appliance.mydomain.com_
